apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gemini-ingress
  namespace: gemini-namespace
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - 13.234.225.76.nip.io
    secretName: gemini-tls-secret
  rules:
  - host: 13.234.225.76.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gemini-service
            port:
              number: 3000
